<h1 style="text-align: center">📝 Tasks on NumPy Arrays</h1> 

### Task 1: Student Grades Analysis
- Create a 2D NumPy array representing marks of 5 students in 4 subjects.  
- Find:  
    - Average marks per student  
    - Highest marks in each subject  
    - Index of student with the lowest total score  


In [20]:
import numpy as np

s1 = [86, 70, 74, 67]
s2 = [72, 79, 81, 70]
s3 = [70, 66, 65, 79]
s4 = [56, 64, 70, 60]
s5 = [69, 75, 80, 73]

marks_arr = np.array([s1, s2, s3, s4, s5])

avg_per_student = np.mean(marks_arr, axis=1)

for i, avg in enumerate(avg_per_student, start=1):
    print(f"Average marks of Student{i}:", avg)

highest_per_subject = np.max(marks_arr, axis=0)

print("")

for i, highest in enumerate(highest_per_subject, start=1):
    print(f"Highest marks of Subject{i}:", highest)


total_scores = np.sum(marks_arr, axis=1)
lowest = np.argmin(total_scores)

print("\nIndex of student with lowest total score:", lowest)

Average marks of Student1: 74.25
Average marks of Student2: 75.5
Average marks of Student3: 70.0
Average marks of Student4: 62.5
Average marks of Student5: 74.25

Highest marks of Subject1: 86
Highest marks of Subject2: 79
Highest marks of Subject3: 81
Highest marks of Subject4: 79

Index of student with lowest total score: 3


### Task 2: Image Reshaping
- Create a 1D array of size 36 with values from 0–35.
- Reshape it into:
    - A 6×6 matrix
    - Then into a 3D array of shape (3, 3, 4)
- Print the shapes at each step.


In [32]:
array_of_36 = np.arange(36)

shape_change = array_of_36.reshape(6,6)

_3d_array = array_of_36.reshape(3,3,4)


print(f"6*6 matrix:\n {shape_change}")
print(f"\n3d matrix:\n {_3d_array}")

6*6 matrix:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

3d matrix:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


### Task 3: Random Data Simulation
- Generate a 3×4 NumPy array of random integers (1–100).
- Sort each row individually.
- Insert a new column at the end with the row sums.


In [39]:
random_nums = np.random.randint(1, 101, size=(3,4))
print(f"Random numbers:\n {random_nums}")

sorted = np.sort(random_nums, axis=1)
print(f"Sorted:\n {sorted}")

row_sums = np.sum(random_nums, axis=1).reshape(-1, 1)

random_nums = np.hstack((random_nums, row_sums))
print(f"Rows sum:\n {random_nums}")

Random numbers:
 [[ 13 100  63   8]
 [ 46  40  58  63]
 [ 62  67  32   2]]
Sorted:
 [[  8  13  63 100]
 [ 40  46  58  63]
 [  2  32  62  67]]
Rows sum:
 [[ 13 100  63   8 184]
 [ 46  40  58  63 207]
 [ 62  67  32   2 163]]


### Task 4: Splitting & Combining Data
- Create a 1D array of numbers from 1 to 20.
- Split it into 4 equal parts.
- Combine the 2nd and 4th parts into one array.


In [44]:
my_arr = np.arange(1,21)

splited_arr = np.split(my_arr, 4)

for i,p in enumerate(splited_arr):
    print(f"Part {i+1}: {p}")

combined = np.concatenate((splited_arr[1], splited_arr[3]))
print("\nCombined 2nd and 4th parts:\n", combined)

Part 1: [1 2 3 4 5]
Part 2: [ 6  7  8  9 10]
Part 3: [11 12 13 14 15]
Part 4: [16 17 18 19 20]

Combined 2nd and 4th parts:
 [ 6  7  8  9 10 16 17 18 19 20]


### Task 5: Data Cleaning with NumPy
- Given an array:
- arr = np.array([12, -5, 0, 23, -15, 45, 30, -2])
- Remove all negative numbers.
- Insert the value 99 at index 2.
- Sort the final array in ascending order.


In [53]:
arr = np.array([12, -5, 0, 23, -15, 45, 30, -2])
arr = arr[arr >= 0]
print("Array after deleting negative numbers:\n", arr)

arr = np.insert(arr, 2, 99)
print("Array after insertion:\n", arr)

arr = np.sort(arr)

print("Final array:\n", arr)


Array after deleting negative numbers:
 [12  0 23 45 30]
Array after insertion:
 [12  0 99 23 45 30]
Final array:
 [ 0 12 23 30 45 99]


### Task 6: Stock Price Analysis (3D Array)
- Create a 3D NumPy array of shape (2, 5, 3) representing stock prices:
    - 2 companies
    - 5 days
    - 3 features: [Open, High, Close]
- Find:
    - Maximum closing price for each company
    - Day index when each company’s stock opened lowest


In [79]:
stock_prices = np.random.randint(100, 501, size=(2,5,3))

print("Stocks\n", stock_prices)

close = stock_prices[:,:,2]

max_close = np.max(close, axis=1)

print("\nMaximum closing price for each company:", max_close)

open = stock_prices[:,:,0]
lowest_open_day = np.argmin(open, axis=1)
print("\nDay index of lowest open price of each company:", lowest_open_day)

Stocks
 [[[237 264 470]
  [292 167 366]
  [466 471 441]
  [361 390 130]
  [452 396 468]]

 [[397 269 169]
  [195 217 478]
  [452 142 450]
  [267 107 278]
  [121 296 159]]]

Maximum closing price for each company: [470 478]

Day index of lowest open price of each company: [0 4]
